version: "3.8"

services:
  app:
    container_name: rgt-bookstore-frontend
    build:
      context: .
      args:
        PUBLIC_API_HOST_URL: ${PUBLIC_API_HOST_URL}
    ports:
      - "3000:3000"
    restart: unless-stopped
